### ISSUE TITLE
EliAuto/EliAutoSell.lua:48: CreateFrame(): Couldn't find inherited node "OptionsButtonTemplate"

### ISSUE THREAD

**Issue by Pahn1988** [Veasst/EliAuto#1]
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/EliAuto/EliAutoSell.lua"]:48: in function <Interface/AddOns/EliAuto/EliAutoSell.lua:42>

Locals:
(*temporary) = "Button"
(*temporary) = nil
(*temporary) = MerchantFrame {
 0 = <userdata>
 TitleContainer = Frame {
 }
 selectedTab = 1
 numTabs = 2
 SetBorder = <function> defined @Interface/SharedXML/PortraitFrame.lua:62
 layoutType = "PortraitFrameTemplate"
 page = 1
 SetPortraitShown = <function> defined @Interface/SharedXML/PortraitFrame.lua:91
 SetTitleMaxLinesAndHeight = <function> defined @Interface/SharedXML/PortraitFrame.lua:49
 SetPortraitToBag = <function> defined @Interface/SharedXML/PortraitFrame.lua:75
 PortraitContainer = Frame {
 }
 SetPortraitToUnit = <function> defined @Interface/SharedXML/PortraitFrame.lua:71
 SetPortraitAtlasRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:83
 Bg = MerchantFrameBg {
 }
 GetTitleText = <function> defined @Interface/SharedXML/PortraitFrame.lua:28
 SetPortraitTextureRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:79
 SetTitleFormatted = <function> defined @Interface/SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 TopTileStreaks = Texture {
 }
 lastTab = 1
 SetPortraitTexCoord = <function> defined @Interface/SharedXML/PortraitFrame.lua:87
 SetPortraitToAsset = <function> defined @Interface/SharedXML/PortraitFrame.lua:67
 SetPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:95
 SetTitleColor = <function> defined @Interface/SharedXML/PortraitFrame.lua:32
 CloseButton = MerchantFrameCloseButton {
 }
 Tabs = <table> {
 }
 GetPortrait = <function> defined @Interface/SharedXML/PortraitFrame.lua:58
 Inset = MerchantFrameInset {
 }
 DefaultPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:101
 SetTitle = <function> defined @Interface/SharedXML/PortraitFrame.lua:36
 lootFilter = MerchantFrameLootFilter {
 }
}
(*temporary) = "OptionsButtonTemplate"

**Comment by Eliviel** [comment]
Fixed in 10.0.0.1
